### ISSUE TITLE
configure ssh 

### ISSUE THREAD

**Issue by razekmh** [Central-Asian-Archaeological-Landscapes/CAAL-Arches-5#15]
We need to configure ssh agent on the server to make it a bit more secure:
- change the ssh access port
- allow access from a specific list of users
- disable root ssh

**Comment by razekmh** [comment]
`root` can no longer ssh to the server and password authentication is not allowed too. Logging to the server requires the use of ssh keys and that your users is added to `sshusers` group. If you require ssh access to the server please do let me know and I will create a user for you. If you require sudo access please do let me know and this will be granted to your user too. You will need to (generate an ssh key)[https://www.ssh.com/academy/ssh/keygen] pair and send me the public key to associate with your user 
@BAPAlveyCHIC I am creating a new user for you but we will need to go through accessing the server as now the port has changed and we will need a new ssh key too.

**Comment by BAPAlveyCHIC** [comment]
Happy to do this on Monday, if you are around.
  
Are you free?
  
I have guests now...
  

  

  

  
  
  
  
  
>
